import { Store, Finished, Winners, Won } from "../Types/type";
import { Anim } from "../Types/type";

export const store: Store = {
  cars: [],
  carCount: 0,
  pageNumber: 1,
  items: 7,
};

export const animationStore: Anim = {
  animation: null,
  id: null,
};

export const finished: Finished[] = [];
export const firstFinished: Finished = {
  finishedCar: null,
  timeAnim: null,
};

export const animArr: Anim[] = [];

export const wins: Won[] = [];

export const winners: Winners = {
  pageNumber: 1,
  items: 10,
};

export const carNames: string[] = [
  "Toyota Corolla",
  "Honda Civic",
  "Ford Fusion",
  "Chevrolet Cruze",
  "Volkswagen Jetta",
  "BMW 3 Series",
  "Mercedes-Benz C-Class",
  "Audi A4",
  "Lexus IS",
  "Hyundai Elantra",
  "Kia Optima",
  "Nissan Altima",
  "Subaru Impreza",
  "Mazda Mazda3",
  "Tesla Model 3",
  "Volvo S60",
  "Genesis G70",
  "Infiniti Q50",
  "Acura ILX",
  "Cadillac CT4",
  "Lincoln MKZ",
  "Buick Regal",
  "Chrysler 200",
  "Dodge Dart",
  "Jeep Compass",
  "Ram 1500",
  "GMC Terrain",
  "Land Rover Range Rover Evoque",
  "Jaguar XE",
  "Porsche Macan",
  "Ferrari 488 GTB",
  "Lamborghini Huracan",
  "McLaren 720S",
  "Bugatti Chiron",
  "Aston Martin DB11",
  "Maserati Ghibli",
  "Bentley Continental GT",
  "Rolls-Royce Phantom",
  "Alfa Romeo Giulia",
  "Lotus Evora",
  "Fiat 500",
  "Smart ForTwo",
  "Mini Cooper",
  "Suzuki Swift",
  "Mitsubishi Lancer",
  "Peugeot 308",
  "Renault Megane",
  "Citroen C4",
  "Skoda Octavia",
  "Seat Leon",
  "Fiat Tipo",
  "Opel Astra",
  "Ford Focus",
  "Volvo V40",
  "Volkswagen Golf",
  "Hyundai i30",
  "Kia Ceed",
  "Honda Civic",
  "Toyota Corolla",
  "Mazda Mazda3",
  "Nissan Sentra",
  "Subaru Impreza",
  "Mitsubishi Lancer",
  "Acura ILX",
  "Lexus IS",
  "Infiniti Q50",
  "Genesis G70",
  "Tesla Model 3",
  "Buick Verano",
  "Chevrolet Malibu",
  "Ford Fusion",
  "Chrysler 300",
  "Dodge Charger",
  "Nissan Maxima",
  "Toyota Camry",
  "Honda Accord",
  "Volkswagen Passat",
  "Hyundai Sonata",
  "Kia Optima",
  "Subaru Legacy",
  "Mazda Mazda6",
  "Audi A6",
  "BMW 5 Series",
  "Mercedes-Benz E-Class",
  "Jaguar XF",
  "Volvo S90",
  "Lincoln Continental",
  "Cadillac CTS",
  "Acura TLX",
  "Infiniti Q70",
  "Genesis G80",
  "Tesla Model S",
  "Porsche Panamera",
  "Maserati Quattroporte",
  "Lexus GS",
  "Aston Martin Rapide",
  "Bentley Flying Spur",
  "Rolls-Royce Ghost",
  "Mercedes-Benz S-Class",
  "BMW 7 Series",
];
